CREATE TABLE users
(
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                      VARCHAR(100)     NOT NULL,
    surname                   VARCHAR(100)     NOT NULL,
    email                     VARCHAR(255)     NOT NULL UNIQUE,
    address                   VARCHAR(255)     NOT NULL,
    alerting                  BOOLEAN          NOT NULL DEFAULT FALSE,
    energy_alerting_threshold DOUBLE PRECISION NOT NULL DEFAULT 0
);
